# Generated by Django 3.0.2 on 2020-08-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_assignment_marks',
            new_name='subject_final_term',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_exam_marks',
            new_name='subject_mid_term',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_sessional_marks',
            field=models.FloatField(default=0),
        ),
    ]
